parameters:
    database_host: 127.0.0.1
    database_port: ~
    database_name: todolistTest
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: test@test.com
    mailer_password: testtest
    secret: ThisTokenIsNotSoSecretChangeIt
