to_do_lists:
    path:     /
    defaults: { _controller: AppBundle:ToDoList:index }
to_do_list_add:
    path:     /to-do-list/add
    defaults: { _controller: AppBundle:ToDoList:new }
to_do_list_update:
    path:     /to-do-list/update/{id}
    defaults: { _controller: AppBundle:ToDoList:update }
to_do_list_delete:
    path:     /to-do-list/delete/{id}
    defaults: { _controller: AppBundle:ToDoList:delete }

tasks:
    path:     /tasks/{listId}
    defaults: { _controller: AppBundle:Task:index }
task_add:
    path:     /task/add/{listId}
    defaults: { _controller: AppBundle:Task:new }
task_update:
    path:     /task/update/{id}
    defaults: { _controller: AppBundle:Task:update }
task_delete:
    path:     /task/delete/{id}
    defaults: { _controller: AppBundle:Task:delete }
task_mark_as_done:
    path:     /task/mark-as-done/{id}
    defaults: { _controller: AppBundle:Task:markTaskAsDone }